#+title: Crater
#+subtitle: Crater is a media gallery
#+export_file_name: index
#+setupfile: ~/.emacs.d/org-templates/projects.org

| Website         | https://andinus.unfla.me/projects/crater |
| Source          | https://git.unfla.me/crater              |
| GitHub (mirror) | https://github.com/andinus/crater        |

Crater is a media gallery.

* Design

- This is the roadmap for v0.2.0. It is a work in-progress.

Crater is a web application to view media gallery. It allows to create
/sharing albums/ to share gallery with others.

On creating a /sharing album/ it will generate an access code, others can
use the access code to view the specific album.

** Authorization

*** Admin

The CLI will generate a random code for admin login.

Admin will be able to view the entire media gallery. They will also be
able to add pictures to a /sharing album/ and view the access code for it.

*** Guests

Guests will have to enter the access code. On authorization the page
will be rendered with all the images that has been added to the /sharing
album/.

** View

The landing page could have statistics and a sidebar that points to the
photos.

We could show the entire gallery in a single page. The images can be
restricted to ~n~ (set by user) and user can load more.

There could be filters (by name, date, etc.) and sorting.

I'm thinking of a page like:
#+begin_src
2022

June
---- pictures ----
May
---- pictures ----


2020

December
---- pictures ----
#+end_src

* History

Initially I planned to make a simple gallery to share pictures with
friends. The idea was to share my pictures, writings with friends for a
specific trip.

I released ~v0.1.0~ that does achieve this. Specific directories can be
shared easily along with writings. It displays pictures in pretty
masonry layout.

I want to expand this to make a media gallery that I can use to view my
pictures/videos. And I also want to be able to create album out of them
and share it with my friends.

I'm creating this because I don't have a way to viewing my media
gallery. My primary computer runs OpenBSD. It initially was for me to
share pictures with friends and web was a good platform for that. I
think it's a good platform for this purpose as well.

* License

#+begin_src
Crater - Crater is a media gallery
Copyright (C) 2021, 2022 Andinus <andinus@nand.sh>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
#+end_src
